#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run prettier on staged files, then tests
yarn --cwd backend lint-staged
yarn --cwd backend test:run
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run tests on pre-commit (run tests in backend)
yarn --cwd backend test:run
